project:
  type: website
  output-dir: docs

website:
  title: "Quarto WNAR 2025"
  navbar:
    background: primary
    foreground: "#fff"
    logo: "/images/web/cat_laptop.gif"
    search: true
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home
    right:
      - href: about.qmd
        text: About
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Workshop slides as "blog"
      - section: "Section for slides"
        contents: 
          - href: slides/part1_overview.qmd
            text: 1 Overview
          - href: slides/part2_presentations.qmd
            text: 2 Presentations
          - href: slides/part3_webpages.qmd
            text: 3 Websites

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # title-prefix: ""
    # pagetitle: "{{< meta title >}}"



