project:
  type: website
  output-dir: docs

website:
  title: "Quarto WNAR 2025"
  navbar:
    background: primary
    foreground: "#fff"
    logo: "/images/web/cat_laptop.gif"
    search: true
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home
    right:
      - href: about.qmd
        text: About
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Workshop slides
      # - href: webpages.qmd
        # text: Webpages        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # title-prefix: ""
    # pagetitle: "{{< meta title >}}"



