---
title: "Part 2: Creating Presentations with Quarto"
subtitle: "WNAR Workshop 2025"
author: "Jessica Minnier, PhD, Meike Niederhausen, PhD"
institute: "OHSU-PSU School of Public Health"
date: "6/15/25"
format: 
  revealjs:
      incremental: false
      scrollable: true
      chalkboard: true
      theme: [sky_modified.scss]
      width:  1050 #default 1050
      height: 700 #default 700
      slide-number: true
      html-math-method: mathjax
  # html:
  #   link-external-newwindow: true
  #   toc: true
execute:
  echo: true
  freeze: auto  # re-render only when source changes
# editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: "setup" 
#| include: false
#| message: false
#| warning: false

library(tidyverse)    
library(oibiostat)
library(janitor)
library(rstatix)
library(knitr)
library(gtsummary)
library(moderndive)
library(gt)
library(broom) 
library(here) 
library(pwr) 

# terminal: for icons
# quarto install extension quarto-ext/fontawesome

# set ggplot theme for slides 
theme_set(theme_bw(base_size = 22))
# theme_update(text = element_text(size=16))  # set global text size for ggplots

```


## Outline


## Create project

regular R project
Mention difference with Quarto project


## YAML 


# Basics

## Html jsreveal slides


## How to create a new slide

## Header/title  slide vs regular slide

## “Scrolling” slide vs not

## Lists

## Tables

## Columns

## Tabs


## Adding images; resizing

## Code & output


### Output in next column or next slide

### Revealing code

### Highlighting out code

### Collapsing code

## Callout blocks

## Revealing stepwise

# Markup


## Font size

### Whole document vs. Whole slide vs. part of slide

### Code font size vs. output font size

### Slide headers font size


## Font color within document: [  ]{style="color:green"}

* Personalize in a scss file??
    * `$theme-green: #40ab16;`

## Themes and title slide material (YAML)

### Scss file - how to modify - later on??

# Presentation tools

https://quarto.org/docs/presentations/revealjs/presenting.html 

## Annotations

saving json & adding annotations back in

## Chalkboard

## Outlines

## Speaker notes 

(like PPT notes; how to do this?)

# Formats

## html (Reveal JS)

### Existing quarto report to slides

## PowerPoint

## LaTeX Beamer slides

# Extra?

* Tips on converting Rmd to Quarto
* Convert jsreveal slides to code file (Meike: look at notes)
* Convert to PDF (and when you can’t)
* Icons
* Hosting on github or netlify; quarto pub (requires quarto pub account)
* Citations/references
 
